version: '3'

services:
  dynamodb-local:
    build: ./dynamodb
    volumes:
      - "dynamodblocal-data:/home/dynamodblocal/data"
    ports:
      - 8000:8000
    restart: always
    command: -jar DynamoDBLocal.jar -dbPath ./data

volumes:
  dynamodblocal-data:
